version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api/src:/usr/src/api/src
      - ./api/fixtures:/usr/src/api/fixtures
    env_file:
      - ./api/.env

  db:
    image: postgres
    env_file:
      - database.env # configure postgres
    ports:
      - "5432:5432"
    volumes:
      - ./api/pg_data:/var/lib/postgresql/data
