version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api/src:/usr/src/api/src
      - ./api/fixtures:/usr/src/api/fixtures

  db:
    image: postgres
    restart: always
    env_file:
      - database.env # configure postgres
    ports:
      - "5432:5432"
    volumes:
      - ./api/pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - "5050:80"
    volumes:
      - type: bind
        source: ./pgadmin-servers.json
        target: /pgadmin4/servers.json
    restart: unless-stopped
