version: "3.8"

services:
  db:
    image: postgres
    env_file:
      - database.env # configure postgres
    ports:
      - "5432:5432"
    volumes:
      - ./api/pg_data:/var/lib/postgresql/data
    user: "1000:1000"
