FROM node:lts-alpine as build
WORKDIR /usr/src/api
COPY src tsconfig.json package.json yarn.lock ormconfig.json ./
RUN yarn
RUN yarn build

FROM node:lts-alpine as prod
RUN apk add --update --no-cache python3 py3-pip curl bash
RUN apk add --update --no-cache openssh --repository=http://dl-4.alpinelinux.org/alpine/v3.4/main
RUN ln -sf python3 /usr/bin/python
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
ADD ./.profile.d /app/.profile.d
ENV NODE_ENV production 
WORKDIR /usr/bin/api
COPY --from=build /usr/src/api/build ./build
COPY --from=build /usr/src/api/package.json /usr/src/api/yarn.lock /usr/src/api/ormconfig.json ./

RUN yarn
CMD yarn start
EXPOSE 8080
