name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      run: heroku login
    - name: Pushing to Heroku
      run: git subtree push --prefix api heroku master
    