name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      env: 
        api_key: ${{ secrets.HEROKU_API_KEY }}
        email: ${{ secrets.HEROKU_EMAIL }}
      run: heroku container:login 
    - run: heroku container:push -a animapp-v1 prod
    - run: heroku container:release -a animapp-v1 prod  

    